steps:
# Build the container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gitdocs-prod:latest', '.' ]
# Push the container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/gitdocs-prod:latest' ]
# Deploy to cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'gitdocs', '--image', 'gcr.io/$PROJECT_ID/gitdocs-prod:latest', '--port', '80', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/gitdocs-prod:latest
options:
  logging: GCS_ONLY
